---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  labels:
    name: cassandra-svc
spec:
  type: NodePort
  ports:
    - port: 7000
      targetPort: cassandra-server
  selector:
    name: cassandra
