FROM projectatomic/atomicapp:0.4.4

MAINTAINER Varun Joshi <varunj.1011@gmail.com>

LABEL io.projectatomic.nulecule.providers="docker,kubernetes" \
      io.projectatomic.nuleclue.specversion="0.0.2"

ADD /Nulecule /Dockerfile /application-entity/
ADD /artifacts /application-entity/artifacts
